version: '3'
services:
  api:
    build: .
    image: api
    container_name: api
    ports:
      - "$APP_PORT:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/api
    env_file:
      - .env
networks:
  default:
    external:
      name: geoworks_network
