=begin
Simple Inventory API

This is a simple API

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  get 'passwords/edit', to: 'passwords#edit'
  post 'passwords/reset', to: 'passwords#reset'

  namespace 'api' do
    namespace 'v1' do

      get 'projects/synchronization' => 'projects#synchronization', as: :projects_s
      post 'projects/synchronization_update' => 'projects#synchronization_update'
      get 'project_types/list_projects' => 'project_types#list_projects'
      get 'projects/list_data' => 'projects#list_data'
      get 'projects/list_data_children' => 'projects#list_data_children'
      get 'projects/check_row_quantity' => 'projects#check_row_quantity'
      get 'projects/check_row_quantity_children' => 'projects#check_row_quantity_children'
      post 'projects/save_rows' => 'projects#save_rows'
      post 'projects/save_row_children' => 'projects#save_row_children'
      post 'projects/update_rows' => 'projects#update_rows'
      post 'passwords/forgot', to: 'passwords#forgot'
      post 'users/update_password', to: 'users#update_password'
      resources :users
      resources :project_fields
      resources :project_types
      resources :sessions, only: [:create, :destroy]
      resources :projects
      # devise_for :users

    end
  end
end
